name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
 contents: read
 deployments: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        export PYTHONPATH=pet_preform_detection
        pytest

    - name: Build release distributions
      run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install build
          python -m build   
          
    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
          name: release-dists
          path: dist/       

    deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to production
        # добавь шаги для деплоя (например, в Docker, на сервер и т.п.)
        run: |
          python -m build